import type { FieldDefinition } from '../types/editor.types';

/**
 * DCAT-AP 3.0 compliant schema definitions.
 * Categories follow the DCAT-AP 3 hierarchy:
 *   identification → provenance → coverage → access → distribution
 *
 * Fields with hidden:true are system/technical and never shown in the editor.
 * Fields with readonly:true and no hidden flag may be shown but not edited.
 */
export function useJsonLdSchema() {
    const datasetSchema: Record<string, FieldDefinition> = {
        // ── System fields (hidden) ─────────────────────────────────────────
        '@id': {
            key: '@id',
            label: 'Dataset ID',
            type: 'uri',
            xsdType: 'xsd:string',
            required: true,
            readonly: true,
            repeatable: false,
            hidden: true,
            autoGenerate: true,
            category: 'technical',
            description: 'Automatically generated unique identifier',
        },
        '@type': {
            key: '@type',
            label: 'Type',
            type: 'string',
            xsdType: 'xsd:string',
            required: true,
            readonly: true,
            repeatable: false,
            hidden: true,
            category: 'technical',
            defaultValue: 'dcat:Dataset',
        },
        'dspace:region': {
            key: 'dspace:region',
            label: 'Region',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            hidden: true,
            category: 'technical',
        },
        'dspace:isDeleted': {
            key: 'dspace:isDeleted',
            label: 'Is Deleted',
            type: 'boolean',
            xsdType: 'xsd:boolean',
            required: false,
            readonly: true,
            repeatable: false,
            hidden: true,
            category: 'technical',
        },
        'dspace:isShared': {
            key: 'dspace:isShared',
            label: 'Is Shared',
            type: 'boolean',
            xsdType: 'xsd:boolean',
            required: false,
            readonly: true,
            repeatable: false,
            hidden: true,
            category: 'technical',
        },
        'dspace:metadataFilename': {
            key: 'dspace:metadataFilename',
            label: 'Metadata Filename',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            hidden: true,
            category: 'technical',
        },
        'dspace:extraMetadata': {
            key: 'dspace:extraMetadata',
            label: 'Extra Metadata',
            type: 'array',
            required: false,
            readonly: true,
            repeatable: false,
            hidden: true,
        },

        // ── IDENTIFICATION ─────────────────────────────────────────────────
        // DCAT-AP 3: title (M), description (M), identifier (E), keyword (A), theme (A)
        'dcterms:title': {
            key: 'dcterms:title',
            label: 'Title',
            type: 'language-string',
            required: true,
            readonly: false,
            repeatable: false,
            category: 'identification',
            dcatApCompliance: 'mandatory',
            description: 'The name of the dataset — be specific enough for a stranger to know what it contains',
            placeholder: 'e.g. Monthly Air Quality Measurements Amsterdam 2020–2024',
        },
        'dcterms:description': {
            key: 'dcterms:description',
            label: 'Description',
            type: 'language-string',
            required: true,
            readonly: false,
            repeatable: false,
            category: 'identification',
            dcatApCompliance: 'mandatory',
            description: 'Explain what the dataset contains, why it was collected, and who would find it useful',
            placeholder: 'e.g. Hourly PM2.5 readings from 12 sensor stations across Amsterdam, collected by the Municipality Environmental Service from Jan 2020 to Dec 2024.',
        },
        'dcterms:identifier': {
            key: 'dcterms:identifier',
            label: 'Identifier',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'identification',
            dcatApCompliance: 'recommended',
            description: 'A unique identifier of the dataset (e.g. internal ID)',
            placeholder: 'e.g., clinical-gwas-cardiology-001',
        },
        'dcat:keyword': {
            key: 'dcat:keyword',
            label: 'Keywords',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'identification',
            dcatApCompliance: 'recommended',
            description: 'Search tags that help people discover this dataset — add one per field',
            placeholder: 'e.g. air quality, PM2.5, environment, Amsterdam',
        },
        'dcat:theme': {
            key: 'dcat:theme',
            label: 'Theme / Category',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'identification',
            dcatApCompliance: 'recommended',
            description: 'The main category of the dataset (from EU Data Themes vocabulary)',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Theme URI',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    vocabulary: 'theme',
                    placeholder: 'http://publications.europa.eu/resource/authority/data-theme/HEAL',
                    description: 'URI from the EU Data Theme vocabulary (e.g. HEAL for Health)',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'skos:Concept',
                },
                'skos:prefLabel': {
                    key: 'skos:prefLabel',
                    label: 'Label',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
            },
        },
        'dcterms:type': {
            key: 'dcterms:type',
            label: 'Dataset Type',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'identification',
            dcatApCompliance: 'optional',
            description: 'The nature or classification of the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Type URI',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'http://purl.org/dc/dcmitype/Dataset',
                },
                '@type': {
                    key: '@type',
                    label: 'Concept Type',
                    type: 'string',
                    required: true,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'skos:Concept',
                },
                'skos:prefLabel': {
                    key: 'skos:prefLabel',
                    label: 'Label',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: { '@language': 'en', '@value': 'Dataset' },
                },
            },
        },
        'dcat:landingPage': {
            key: 'dcat:landingPage',
            label: 'Landing Page',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'identification',
            dcatApCompliance: 'optional',
            description: 'A webpage that gives access to the dataset and additional information',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Page URL',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'https://example.com/dataset',
                },
            },
        },

        // ── PROVENANCE ─────────────────────────────────────────────────────
        // DCAT-AP 3: publisher (E), creator (A), issued, modified, version
        'dcterms:publisher': {
            key: 'dcterms:publisher',
            label: 'Publisher',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'provenance',
            dcatApCompliance: 'recommended',
            description: 'The organisation responsible for making the dataset available',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Organisation URI',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'https://ror.org/...',
                    description: 'Linked identifier of the publishing organisation',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'foaf:Agent',
                },
                'foaf:name': {
                    key: 'foaf:name',
                    label: 'Organisation Name',
                    type: 'string',
                    xsdType: 'xsd:string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'e.g., Amsterdam UMC',
                },
            },
        },
        'dcterms:creator': {
            key: 'dcterms:creator',
            label: 'Creator',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'provenance',
            dcatApCompliance: 'optional',
            description: 'The person or organisation that created the dataset',
            children: {
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'foaf:Agent',
                },
                'foaf:name': {
                    key: 'foaf:name',
                    label: 'Name',
                    type: 'string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'e.g., Dr. Jane Smith',
                    description: 'Name of the creator (person or organisation)',
                },
            },
        },
        'dcterms:issued': {
            key: 'dcterms:issued',
            label: 'Release Date',
            type: 'date',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            hidden: true, // Auto-managed by the system
            category: 'provenance',
        },
        'dcterms:modified': {
            key: 'dcterms:modified',
            label: 'Last Updated',
            type: 'date',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'provenance',
            dcatApCompliance: 'recommended',
            description: 'The date on which the dataset was most recently changed',
        },
        'dcat:version': {
            key: 'dcat:version',
            label: 'Version',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'provenance',
            dcatApCompliance: 'optional',
            description: 'Version number or name of this dataset',
            placeholder: 'e.g., 1.0.0',
        },
        'dcterms:accrualPeriodicity': {
            key: 'dcterms:accrualPeriodicity',
            label: 'Update Frequency',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'provenance',
            dcatApCompliance: 'optional',
            description: 'How often the dataset is updated',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Frequency',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    vocabulary: 'frequency',
                    placeholder: 'http://publications.europa.eu/resource/authority/frequency/ANNUAL',
                    description: 'URI from the MDR Frequency Named Authority List',
                },
            },
        },
        'dcat:inSeries': {
            key: 'dcat:inSeries',
            label: 'Part of Dataset Series',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'provenance',
            dcatApCompliance: 'optional',
            description: 'The dataset series this dataset belongs to',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Series URI',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcat:DatasetSeries',
                },
                'dcterms:title': {
                    key: 'dcterms:title',
                    label: 'Series Title',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                'dcterms:description': {
                    key: 'dcterms:description',
                    label: 'Series Description',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
            },
        },

        // ── COVERAGE ───────────────────────────────────────────────────────
        // DCAT-AP 3: spatial (E), temporal (E), language (E)
        'dcterms:spatial': {
            key: 'dcterms:spatial',
            label: 'Geographical Coverage',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'coverage',
            dcatApCompliance: 'recommended',
            description: 'The geographic area(s) covered by the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Location',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'http://sws.geonames.org/2950159/',
                    description: 'URI of the geographic location (e.g., from GeoNames or EU Vocabularies)',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:Location',
                },
            },
        },
        'dcterms:temporal': {
            key: 'dcterms:temporal',
            label: 'Time Period Covered',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'coverage',
            dcatApCompliance: 'recommended',
            description: 'The time period(s) covered by the data',
            children: {
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:PeriodOfTime',
                },
                'dcat:startDate': {
                    key: 'dcat:startDate',
                    label: 'Start Date',
                    type: 'date',
                    xsdType: 'xsd:date',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: '2024-01-01',
                    description: 'Start date of the covered period',
                },
                'dcat:endDate': {
                    key: 'dcat:endDate',
                    label: 'End Date',
                    type: 'date',
                    xsdType: 'xsd:date',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: '2024-12-31',
                    description: 'End date of the covered period',
                },
            },
        },
        'dcterms:language': {
            key: 'dcterms:language',
            label: 'Language',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'coverage',
            dcatApCompliance: 'recommended',
            description: 'The language(s) in which the dataset is available',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Language',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    vocabulary: 'language',
                    placeholder: 'http://publications.europa.eu/resource/authority/language/ENG',
                    description: 'Language code from EU Vocabularies (e.g., ENG, NLD, DEU)',
                },
            },
        },

        // ── ACCESS ─────────────────────────────────────────────────────────
        // DCAT-AP 3: accessRights (E), license, contactPoint (A)
        'dcterms:accessRights': {
            key: 'dcterms:accessRights',
            label: 'Access Rights',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'access',
            dcatApCompliance: 'recommended',
            description: 'Who can access the dataset (Public, Restricted, Non-Public)',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Access Rights Level',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    vocabulary: 'accessRights',
                    placeholder: 'http://publications.europa.eu/resource/authority/access-right/PUBLIC',
                    description: 'Select: PUBLIC, RESTRICTED, or NON_PUBLIC',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:RightsStatement',
                },
            },
        },
        'dcterms:license': {
            key: 'dcterms:license',
            label: 'Licence',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'access',
            dcatApCompliance: 'optional',
            description: 'The licence under which the dataset is shared',
            placeholder: 'e.g., CC-BY-4.0, EUPL-1.2',
        },
        'dcat:contactPoint': {
            key: 'dcat:contactPoint',
            label: 'Contact Point',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'access',
            dcatApCompliance: 'recommended',
            description: 'Contact information for questions about the dataset',
            children: {
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: true,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'vcard:Kind',
                },
                'vcard:fn': {
                    key: 'vcard:fn',
                    label: 'Contact Name',
                    type: 'string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'e.g., Dr. Jane Smith or Data Access Office',
                    description: 'Full name of the contact (person or team)',
                },
                'vcard:hasEmail': {
                    key: 'vcard:hasEmail',
                    label: 'Email Address',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'mailto:contact@example.com',
                    description: 'Email address (must start with mailto:)',
                },
                'vcard:hasTelephone': {
                    key: 'vcard:hasTelephone',
                    label: 'Phone Number',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'tel:+31-20-555-0100',
                    description: 'Phone number (must start with tel:)',
                },
                'vcard:hasURL': {
                    key: 'vcard:hasURL',
                    label: 'Website',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'https://example.com/contact',
                    description: 'Contact or information page URL',
                },
            },
        },

        // ── DISTRIBUTION ───────────────────────────────────────────────────
        'dcat:distribution': {
            key: 'dcat:distribution',
            label: 'Distributions',
            type: 'array',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'distribution',
            dcatApCompliance: 'optional',
            description: 'Available file formats / access points for this dataset',
        },
    };

    const distributionSchema: Record<string, FieldDefinition> = {
        '@id': {
            key: '@id',
            label: 'Distribution ID',
            type: 'uri',
            required: false,
            readonly: true,
            repeatable: false,
            hidden: true,
            autoGenerate: true,
            description: 'Automatically generated unique identifier',
        },
        '@type': {
            key: '@type',
            label: 'Type',
            type: 'string',
            required: true,
            readonly: true,
            repeatable: false,
            hidden: true,
            defaultValue: 'dcat:Distribution',
        },
        'dcat:accessURL': {
            key: 'dcat:accessURL',
            label: 'Access URL',
            type: 'object',
            required: true,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'mandatory',
            description: 'The URL that gives access to this distribution',
            children: {
                '@id': {
                    key: '@id',
                    label: 'URL',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'https://example.com/data or file://path/to/file',
                },
            },
        },
        'dcat:downloadURL': {
            key: 'dcat:downloadURL',
            label: 'Download URL',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'optional',
            description: 'Direct download link for this distribution',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Download URL',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'https://example.com/data.csv',
                },
            },
        },
        'dcterms:title': {
            key: 'dcterms:title',
            label: 'Distribution Title',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'optional',
            placeholder: 'e.g., CSV Export, DICOM Archive',
        },
        'dcterms:description': {
            key: 'dcterms:description',
            label: 'Description',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'optional',
            placeholder: 'Describe this distribution',
        },
        'dcat:mediaType': {
            key: 'dcat:mediaType',
            label: 'Media Type',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'recommended',
            vocabulary: 'fileType',
            placeholder: 'e.g., text/csv, application/json',
            description: 'IANA media type of the distribution',
        },
        'dcat:format': {
            key: 'dcat:format',
            label: 'Format',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'recommended',
            placeholder: 'e.g., CSV, JSON, DICOM, NIfTI',
        },
        'dcat:byteSize': {
            key: 'dcat:byteSize',
            label: 'File Size (bytes)',
            type: 'number',
            xsdType: 'xsd:nonNegativeInteger',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'optional',
            placeholder: '0',
        },
        'dcterms:license': {
            key: 'dcterms:license',
            label: 'Licence',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'recommended',
            description: 'The licence for this specific distribution',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Licence URI',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'http://creativecommons.org/licenses/by/4.0/',
                    description: 'URI of the licence',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:LicenseDocument',
                },
            },
        },
        'data:availability': {
            key: 'data:availability',
            label: 'Availability',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'recommended',
            description: 'Planned availability of this distribution',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Availability',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    vocabulary: 'availability',
                    placeholder: 'http://publications.europa.eu/resource/authority/planned-availability/AVAILABLE',
                },
            },
        },
        'dcterms:issued': {
            key: 'dcterms:issued',
            label: 'Release Date',
            type: 'date',
            xsdType: 'xsd:dateTime',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'optional',
        },
        'dcterms:modified': {
            key: 'dcterms:modified',
            label: 'Last Updated',
            type: 'date',
            xsdType: 'xsd:dateTime',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'optional',
        },
        'spdx:checksum': {
            key: 'spdx:checksum',
            label: 'Checksum',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            dcatApCompliance: 'optional',
            description: 'Checksum to verify file integrity',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Checksum ID',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    hidden: true,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'spdx:Checksum',
                },
                'spdx:algorithm': {
                    key: 'spdx:algorithm',
                    label: 'Algorithm',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    vocabulary: 'algorithm',
                    placeholder: 'e.g. SHA-256',
                },
                'spdx:checksumValue': {
                    key: 'spdx:checksumValue',
                    label: 'Checksum Value',
                    type: 'string',
                    xsdType: 'xsd:hexBinary',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'Hexadecimal checksum value',
                },
            },
        },
    };

    const getFieldDefinition = (key: string, context: 'dataset' | 'distribution' = 'dataset'): FieldDefinition | undefined => {
        const schema = context === 'dataset' ? datasetSchema : distributionSchema;

        // Depth-first recursive search through the schema tree
        const searchSchema = (fields: Record<string, FieldDefinition>): FieldDefinition | undefined => {
            if (fields[key]) return fields[key];
            for (const fieldDef of Object.values(fields)) {
                if (fieldDef.children) {
                    const found = searchSchema(fieldDef.children);
                    if (found) return found;
                }
            }
            return undefined;
        };

        return searchSchema(schema);
    };

    const getRequiredFields = (context: 'dataset' | 'distribution' = 'dataset'): string[] => {
        const schema = context === 'dataset' ? datasetSchema : distributionSchema;
        return Object.entries(schema)
            .filter(([_, def]) => def.required)
            .map(([key]) => key);
    };

    const getReadonlyFields = (): string[] => {
        return Object.entries(datasetSchema)
            .filter(([_, def]) => def.readonly)
            .map(([key]) => key);
    };

    /**
     * Returns all fields available for the DCAT-AP guided "Add Field" picker.
     * Excludes hidden/technical fields.
     */
    const getAddableFields = (context: 'dataset' | 'distribution' = 'dataset'): FieldDefinition[] => {
        const schema = context === 'dataset' ? datasetSchema : distributionSchema;
        return Object.values(schema).filter(def => !def.hidden && !def.readonly);
    };

    return {
        datasetSchema,
        distributionSchema,
        getFieldDefinition,
        getRequiredFields,
        getReadonlyFields,
        getAddableFields,
    };
}
