import type { FieldDefinition } from '../types/editor.types';

export function useJsonLdSchema() {
    const datasetSchema: Record<string, FieldDefinition> = {
        '@id': {
            key: '@id',
            label: 'Dataset ID',
            type: 'uri',
            xsdType: 'xsd:string',
            required: true,
            readonly: true,
            repeatable: false,
            autoGenerate: true,
            category: 'technical',
            description: 'Automatically generated unique identifier',
        },
        '@type': {
            key: '@type',
            label: 'Type',
            type: 'string',
            xsdType: 'xsd:string',
            required: true,
            readonly: true,
            repeatable: false,
            hidden: true,
            category: 'technical',
            defaultValue: 'dcat:Dataset',
        },
        'dcterms:identifier': {
            key: 'dcterms:identifier',
            label: 'Identifier',
            type: 'string',
            xsdType: 'xsd:string',
            required: true,
            readonly: false,
            repeatable: false,
            category: 'basic',
            description: 'A unique identifier of the dataset',
            placeholder: 'e.g., clinical-gwas-cardiology-001',
        },
        'dcterms:title': {
            key: 'dcterms:title',
            label: 'Title',
            type: 'language-string',
            required: true,
            readonly: false,
            repeatable: false,
            category: 'basic',
            description: 'A name given to the dataset',
            placeholder: 'Enter dataset title',
        },
        'dcterms:description': {
            key: 'dcterms:description',
            label: 'Description',
            type: 'language-string',
            required: true,
            readonly: false,
            repeatable: false,
            category: 'basic',
            description: 'A free-text account of the dataset',
            placeholder: 'Enter dataset description',
        },
        'dcterms:type': {
            key: 'dcterms:type',
            label: 'Type',
            type: 'object',
            required: true,
            readonly: false,
            repeatable: false,
            description: 'The type of the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Type URI',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'http://purl.org/dc/dcmitype/Dataset',
                },
                '@type': {
                    key: '@type',
                    label: 'Concept Type',
                    type: 'string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'skos:Concept',
                },
                'skos:prefLabel': {
                    key: 'skos:prefLabel',
                    label: 'Label',
                    type: 'language-string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    defaultValue: { '@language': 'en', '@value': 'Dataset' },
                },
            },
        },
        'dcterms:issued': {
            key: 'dcterms:issued',
            label: 'Issued Date',
            type: 'date',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            category: 'basic',
            description: 'Date of formal issuance of the dataset',
        },
        'dcterms:modified': {
            key: 'dcterms:modified',
            label: 'Modified Date',
            type: 'date',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'basic',
            description: 'Most recent date on which the dataset was changed',
        },
        'dcat:version': {
            key: 'dcat:version',
            label: 'Version',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'basic',
            description: 'Version number or version name of the dataset',
            placeholder: 'e.g., 1.0.0, v2.1',
        },
        'dcterms:license': {
            key: 'dcterms:license',
            label: 'License',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'rights',
            description: 'A legal document under which the dataset is made available',
            placeholder: 'e.g., EUPL, CC-BY-4.0',
        },
        'dcterms:publisher': {
            key: 'dcterms:publisher',
            label: 'Publisher',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'The entity responsible for making the dataset available',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Publisher ID',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Publisher Type',
                    type: 'array',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: ['foaf:Agent', 'foaf:Organization', 'foaf:Person'],
                },
                'dcterms:identifier': {
                    key: 'dcterms:identifier',
                    label: 'Identifier',
                    type: 'string',
                    xsdType: 'xsd:string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                'foaf:name': {
                    key: 'foaf:name',
                    label: 'Name',
                    type: 'string',
                    xsdType: 'xsd:string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'Publisher name',
                },
            },
        },
        'dcat:keyword': {
            key: 'dcat:keyword',
            label: 'Keywords',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: true,
            description: 'A keyword or tag describing the dataset',
            placeholder: 'Add keyword',
        },
        'dcat:theme': {
            key: 'dcat:theme',
            label: 'Theme',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'A category of the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Theme URI',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'skos:Concept',
                },
                'skos:prefLabel': {
                    key: 'skos:prefLabel',
                    label: 'Label',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
            },
        },
        'dcat:distribution': {
            key: 'dcat:distribution',
            label: 'Distributions',
            type: 'array',
            required: false,
            readonly: false,
            repeatable: true,
            description: 'An available distribution of the dataset',
        },
        'dcat:inSeries': {
            key: 'dcat:inSeries',
            label: 'In Series',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'The dataset series of which the dataset is part',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Series ID',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'dcat:DatasetSeries',
                },
                'dcterms:title': {
                    key: 'dcterms:title',
                    label: 'Title',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                'dcterms:description': {
                    key: 'dcterms:description',
                    label: 'Description',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
            },
        },
        'dcterms:creator': {
            key: 'dcterms:creator',
            label: 'Creator',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'contact',
            description: 'The entity responsible for creating the dataset',
            children: {
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'foaf:Agent',
                },
                'foaf:name': {
                    key: 'foaf:name',
                    label: 'Creator Name',
                    type: 'string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'e.g., John Doe, Research Institute',
                    description: 'Name of the creator (person or organization)',
                },
            },
        },
        'dcat:contactPoint': {
            key: 'dcat:contactPoint',
            label: 'Contact Point',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'contact',
            description: 'Contact information for inquiries about the dataset',
            children: {
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: true,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'vcard:Kind',
                },
                'vcard:fn': {
                    key: 'vcard:fn',
                    label: 'Full Name',
                    type: 'string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'John Doe',
                    description: 'Full name of the contact',
                },
                'vcard:hasEmail': {
                    key: 'vcard:hasEmail',
                    label: 'Email',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'mailto:contact@example.com',
                    description: 'Email address (must start with mailto:)',
                },
                'vcard:hasTelephone': {
                    key: 'vcard:hasTelephone',
                    label: 'Telephone',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'tel:+1-234-567-8900',
                    description: 'Telephone number (must start with tel:)',
                },
                'vcard:hasURL': {
                    key: 'vcard:hasURL',
                    label: 'Website',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'https://example.com',
                    description: 'Website URL',
                },
            },
        },
        'dcterms:spatial': {
            key: 'dcterms:spatial',
            label: 'Spatial Coverage',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'coverage',
            description: 'Geographic area covered by the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Location URI',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'http://sws.geonames.org/2950159/',
                    description: 'URI of the geographic location (e.g., GeoNames)',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:Location',
                },
            },
        },
        'dcterms:temporal': {
            key: 'dcterms:temporal',
            label: 'Temporal Coverage',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'coverage',
            description: 'Time period covered by the dataset',
            children: {
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:PeriodOfTime',
                },
                'dcat:startDate': {
                    key: 'dcat:startDate',
                    label: 'Start Date',
                    type: 'date',
                    xsdType: 'xsd:date',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: '2024-01-01',
                    description: 'Start date of the period',
                },
                'dcat:endDate': {
                    key: 'dcat:endDate',
                    label: 'End Date',
                    type: 'date',
                    xsdType: 'xsd:date',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: '2024-12-31',
                    description: 'End date of the period',
                },
            },
        },
        'dcterms:accessRights': {
            key: 'dcterms:accessRights',
            label: 'Access Rights',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            category: 'rights',
            description: 'Information about who can access the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Access Rights URI',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'http://publications.europa.eu/resource/authority/access-right/PUBLIC',
                    description: 'URI from EU Vocabularies (PUBLIC, RESTRICTED, NON_PUBLIC)',
                    vocabulary: 'accessRights',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:RightsStatement',
                },
            },
        },
        'dcterms:language': {
            key: 'dcterms:language',
            label: 'Language',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: true,
            category: 'basic',
            description: 'Language(s) of the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Language URI',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'http://publications.europa.eu/resource/authority/language/ENG',
                    description: 'URI from EU Vocabularies (ENG, NLD, DEU, FRA, etc.)',
                    vocabulary: 'language',
                },
            },
        },
        'dspace:region': {
            key: 'dspace:region',
            label: 'Region',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            category: 'technical',
            description: 'Backend-managed region identifier',
        },
        'dspace:isDeleted': {
            key: 'dspace:isDeleted',
            label: 'Is Deleted',
            type: 'boolean',
            xsdType: 'xsd:boolean',
            required: false,
            readonly: true,
            repeatable: false,
            category: 'technical',
        },
        'dspace:isShared': {
            key: 'dspace:isShared',
            label: 'Is Shared',
            type: 'boolean',
            xsdType: 'xsd:boolean',
            required: false,
            readonly: true,
            repeatable: false,
            category: 'technical',
        },
        'dspace:metadataFilename': {
            key: 'dspace:metadataFilename',
            label: 'Metadata Filename',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            category: 'technical',
        },
        'dspace:extraMetadata': {
            key: 'dspace:extraMetadata',
            label: 'Extra Metadata',
            type: 'array',
            required: false,
            readonly: true,
            repeatable: false,
            description: 'Semantic metadata from MMIO (read-only)',
        },
    };

    const distributionSchema: Record<string, FieldDefinition> = {
        '@id': {
            key: '@id',
            label: 'Distribution ID',
            type: 'uri',
            required: false,
            readonly: true,
            repeatable: false,
            autoGenerate: true,
            description: 'Automatically generated unique identifier',
        },
        '@type': {
            key: '@type',
            label: 'Type',
            type: 'string',
            required: true,
            readonly: true,
            repeatable: false,
            hidden: true,
            defaultValue: 'dcat:Distribution',
        },
        'dcat:accessURL': {
            key: 'dcat:accessURL',
            label: 'Access URL',
            type: 'object',
            required: true,
            readonly: false,
            repeatable: false,
            description: 'A URL that gives access to the distribution',
            children: {
                '@id': {
                    key: '@id',
                    label: 'URL',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'file://path/to/file or https://...',
                },
            },
        },
        'dcterms:title': {
            key: 'dcterms:title',
            label: 'Title',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: 'Distribution title',
        },
        'dcterms:description': {
            key: 'dcterms:description',
            label: 'Description',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: 'Distribution description',
        },
        'dcat:format': {
            key: 'dcat:format',
            label: 'Format',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: 'e.g., dcm, json, csv',
        },
        'dcat:byteSize': {
            key: 'dcat:byteSize',
            label: 'Byte Size',
            type: 'number',
            xsdType: 'xsd:nonNegativeInteger',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: '0',
        },
        'dcterms:issued': {
            key: 'dcterms:issued',
            label: 'Issued',
            type: 'date',
            xsdType: 'xsd:dateTime',
            required: false,
            readonly: false,
            repeatable: false,
        },
        'dcterms:modified': {
            key: 'dcterms:modified',
            label: 'Modified',
            type: 'date',
            xsdType: 'xsd:dateTime',
            required: false,
            readonly: false,
            repeatable: false,
        },
        'spdx:checksum': {
            key: 'spdx:checksum',
            label: 'Checksum',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            children: {
                '@id': {
                    key: '@id',
                    label: 'Checksum ID',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'spdx:Checksum',
                },
                'spdx:algorithm': {
                    key: 'spdx:algorithm',
                    label: 'Algorithm',
                    type: 'object',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    children: {
                        '@id': {
                            key: '@id',
                            label: 'Algorithm',
                            type: 'uri',
                            required: false,
                            readonly: false,
                            repeatable: false,
                            defaultValue: 'spdx:SHA256',
                        },
                        '@type': {
                            key: '@type',
                            label: 'Type',
                            type: 'string',
                            required: false,
                            readonly: false,
                            repeatable: false,
                            defaultValue: 'spdx:ChecksumAlgorithm',
                        },
                    },
                },
                'spdx:checksumValue': {
                    key: 'spdx:checksumValue',
                    label: 'Checksum Value',
                    type: 'string',
                    xsdType: 'xsd:hexBinary',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'Hexadecimal checksum',
                },
            },
        },
        'dcterms:license': {
            key: 'dcterms:license',
            label: 'License',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'License under which the distribution is made available',
            children: {
                '@id': {
                    key: '@id',
                    label: 'License URI',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'http://creativecommons.org/licenses/by/4.0/',
                    description: 'URI of the license',
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: true,
                    repeatable: false,
                    hidden: true,
                    defaultValue: 'dcterms:LicenseDocument',
                },
            },
        },
    };

    const getFieldDefinition = (key: string, context: 'dataset' | 'distribution' = 'dataset'): FieldDefinition | undefined => {
        const schema = context === 'dataset' ? datasetSchema : distributionSchema;
        return schema[key];
    };

    const getRequiredFields = (context: 'dataset' | 'distribution' = 'dataset'): string[] => {
        const schema = context === 'dataset' ? datasetSchema : distributionSchema;
        return Object.entries(schema)
            .filter(([_, def]) => def.required)
            .map(([key]) => key);
    };

    const getReadonlyFields = (): string[] => {
        return Object.entries(datasetSchema)
            .filter(([_, def]) => def.readonly)
            .map(([key]) => key);
    };

    return {
        datasetSchema,
        distributionSchema,
        getFieldDefinition,
        getRequiredFields,
        getReadonlyFields,
    };
}
