import type { FieldDefinition } from '../types/editor.types';

export function useJsonLdSchema() {
    const datasetSchema: Record<string, FieldDefinition> = {
        '@id': {
            key: '@id',
            label: 'Dataset ID',
            type: 'uri',
            xsdType: 'xsd:string',
            required: true,
            readonly: true,
            repeatable: false,
            description: 'Unique identifier for the dataset',
        },
        '@type': {
            key: '@type',
            label: 'Type',
            type: 'string',
            xsdType: 'xsd:string',
            required: true,
            readonly: true,
            repeatable: false,
            defaultValue: 'dcat:Dataset',
        },
        'dcterms:identifier': {
            key: 'dcterms:identifier',
            label: 'Identifier',
            type: 'string',
            xsdType: 'xsd:string',
            required: true,
            readonly: false,
            repeatable: false,
            description: 'A unique identifier of the dataset',
            placeholder: 'e.g., clinical-gwas-cardiology-001',
        },
        'dcterms:title': {
            key: 'dcterms:title',
            label: 'Title',
            type: 'language-string',
            required: true,
            readonly: false,
            repeatable: false,
            description: 'A name given to the dataset',
            placeholder: 'Enter dataset title',
        },
        'dcterms:description': {
            key: 'dcterms:description',
            label: 'Description',
            type: 'language-string',
            required: true,
            readonly: false,
            repeatable: false,
            description: 'A free-text account of the dataset',
            placeholder: 'Enter dataset description',
        },
        'dcterms:type': {
            key: 'dcterms:type',
            label: 'Type',
            type: 'object',
            required: true,
            readonly: false,
            repeatable: false,
            description: 'The type of the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Type URI',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'http://purl.org/dc/dcmitype/Dataset',
                },
                '@type': {
                    key: '@type',
                    label: 'Concept Type',
                    type: 'string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'skos:Concept',
                },
                'skos:prefLabel': {
                    key: 'skos:prefLabel',
                    label: 'Label',
                    type: 'language-string',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    defaultValue: { '@language': 'en', '@value': 'Dataset' },
                },
            },
        },
        'dcterms:issued': {
            key: 'dcterms:issued',
            label: 'Issued Date',
            type: 'date',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            description: 'Date of formal issuance of the dataset',
        },
        'dcterms:license': {
            key: 'dcterms:license',
            label: 'License',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'A legal document under which the dataset is made available',
            placeholder: 'e.g., EUPL, CC-BY-4.0',
        },
        'dcterms:publisher': {
            key: 'dcterms:publisher',
            label: 'Publisher',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'The entity responsible for making the dataset available',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Publisher ID',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Publisher Type',
                    type: 'array',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: ['foaf:Agent', 'foaf:Organization', 'foaf:Person'],
                },
                'dcterms:identifier': {
                    key: 'dcterms:identifier',
                    label: 'Identifier',
                    type: 'string',
                    xsdType: 'xsd:string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                'foaf:name': {
                    key: 'foaf:name',
                    label: 'Name',
                    type: 'string',
                    xsdType: 'xsd:string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'Publisher name',
                },
            },
        },
        'dcat:keyword': {
            key: 'dcat:keyword',
            label: 'Keywords',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: true,
            description: 'A keyword or tag describing the dataset',
            placeholder: 'Add keyword',
        },
        'dcat:theme': {
            key: 'dcat:theme',
            label: 'Theme',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'A category of the dataset',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Theme URI',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'skos:Concept',
                },
                'skos:prefLabel': {
                    key: 'skos:prefLabel',
                    label: 'Label',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
            },
        },
        'dcat:distribution': {
            key: 'dcat:distribution',
            label: 'Distributions',
            type: 'array',
            required: false,
            readonly: false,
            repeatable: true,
            description: 'An available distribution of the dataset',
        },
        'dcat:inSeries': {
            key: 'dcat:inSeries',
            label: 'In Series',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            description: 'The dataset series of which the dataset is part',
            children: {
                '@id': {
                    key: '@id',
                    label: 'Series ID',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'dcat:DatasetSeries',
                },
                'dcterms:title': {
                    key: 'dcterms:title',
                    label: 'Title',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                'dcterms:description': {
                    key: 'dcterms:description',
                    label: 'Description',
                    type: 'language-string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
            },
        },
        'dspace:region': {
            key: 'dspace:region',
            label: 'Region',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
            description: 'Backend-managed region identifier',
        },
        'dspace:isDeleted': {
            key: 'dspace:isDeleted',
            label: 'Is Deleted',
            type: 'boolean',
            xsdType: 'xsd:boolean',
            required: false,
            readonly: true,
            repeatable: false,
        },
        'dspace:isShared': {
            key: 'dspace:isShared',
            label: 'Is Shared',
            type: 'boolean',
            xsdType: 'xsd:boolean',
            required: false,
            readonly: true,
            repeatable: false,
        },
        'dspace:metadataFilename': {
            key: 'dspace:metadataFilename',
            label: 'Metadata Filename',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: true,
            repeatable: false,
        },
        'dspace:extraMetadata': {
            key: 'dspace:extraMetadata',
            label: 'Extra Metadata',
            type: 'array',
            required: false,
            readonly: true,
            repeatable: false,
            description: 'Semantic metadata from MMIO (read-only)',
        },
    };

    const distributionSchema: Record<string, FieldDefinition> = {
        '@id': {
            key: '@id',
            label: 'Distribution ID',
            type: 'uri',
            required: false,
            readonly: false,
            repeatable: false,
        },
        '@type': {
            key: '@type',
            label: 'Type',
            type: 'string',
            required: true,
            readonly: false,
            repeatable: false,
            defaultValue: 'dcat:Distribution',
        },
        'dcat:accessURL': {
            key: 'dcat:accessURL',
            label: 'Access URL',
            type: 'object',
            required: true,
            readonly: false,
            repeatable: false,
            description: 'A URL that gives access to the distribution',
            children: {
                '@id': {
                    key: '@id',
                    label: 'URL',
                    type: 'uri',
                    required: true,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'file://path/to/file or https://...',
                },
            },
        },
        'dcterms:title': {
            key: 'dcterms:title',
            label: 'Title',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: 'Distribution title',
        },
        'dcterms:description': {
            key: 'dcterms:description',
            label: 'Description',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: 'Distribution description',
        },
        'dcat:format': {
            key: 'dcat:format',
            label: 'Format',
            type: 'string',
            xsdType: 'xsd:string',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: 'e.g., dcm, json, csv',
        },
        'dcat:byteSize': {
            key: 'dcat:byteSize',
            label: 'Byte Size',
            type: 'number',
            xsdType: 'xsd:nonNegativeInteger',
            required: false,
            readonly: false,
            repeatable: false,
            placeholder: '0',
        },
        'dcterms:issued': {
            key: 'dcterms:issued',
            label: 'Issued',
            type: 'date',
            xsdType: 'xsd:dateTime',
            required: false,
            readonly: false,
            repeatable: false,
        },
        'dcterms:modified': {
            key: 'dcterms:modified',
            label: 'Modified',
            type: 'date',
            xsdType: 'xsd:dateTime',
            required: false,
            readonly: false,
            repeatable: false,
        },
        'spdx:checksum': {
            key: 'spdx:checksum',
            label: 'Checksum',
            type: 'object',
            required: false,
            readonly: false,
            repeatable: false,
            children: {
                '@id': {
                    key: '@id',
                    label: 'Checksum ID',
                    type: 'uri',
                    required: false,
                    readonly: false,
                    repeatable: false,
                },
                '@type': {
                    key: '@type',
                    label: 'Type',
                    type: 'string',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    defaultValue: 'spdx:Checksum',
                },
                'spdx:algorithm': {
                    key: 'spdx:algorithm',
                    label: 'Algorithm',
                    type: 'object',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    children: {
                        '@id': {
                            key: '@id',
                            label: 'Algorithm',
                            type: 'uri',
                            required: false,
                            readonly: false,
                            repeatable: false,
                            defaultValue: 'spdx:SHA256',
                        },
                        '@type': {
                            key: '@type',
                            label: 'Type',
                            type: 'string',
                            required: false,
                            readonly: false,
                            repeatable: false,
                            defaultValue: 'spdx:ChecksumAlgorithm',
                        },
                    },
                },
                'spdx:checksumValue': {
                    key: 'spdx:checksumValue',
                    label: 'Checksum Value',
                    type: 'string',
                    xsdType: 'xsd:hexBinary',
                    required: false,
                    readonly: false,
                    repeatable: false,
                    placeholder: 'Hexadecimal checksum',
                },
            },
        },
    };

    const getFieldDefinition = (key: string, context: 'dataset' | 'distribution' = 'dataset'): FieldDefinition | undefined => {
        const schema = context === 'dataset' ? datasetSchema : distributionSchema;
        return schema[key];
    };

    const getRequiredFields = (context: 'dataset' | 'distribution' = 'dataset'): string[] => {
        const schema = context === 'dataset' ? datasetSchema : distributionSchema;
        return Object.entries(schema)
            .filter(([_, def]) => def.required)
            .map(([key]) => key);
    };

    const getReadonlyFields = (): string[] => {
        return Object.entries(datasetSchema)
            .filter(([_, def]) => def.readonly)
            .map(([key]) => key);
    };

    return {
        datasetSchema,
        distributionSchema,
        getFieldDefinition,
        getRequiredFields,
        getReadonlyFields,
    };
}
