import type { FieldDefinition } from "../types/editor.types";

export const distributionSchema: Record<string, FieldDefinition> = {
    '@id': {
        key: '@id',
        label: 'Distribution ID',
        type: 'uri',
        required: false,
        readonly: true,
        repeatable: false,
        hidden: true,
        autoGenerate: true,
        description: 'Automatically generated unique identifier',
    },
    '@type': {
        key: '@type',
        label: 'Type',
        type: 'string',
        required: true,
        readonly: true,
        repeatable: false,
        hidden: true,
        defaultValue: 'dcat:Distribution',
    },
    'dcat:accessURL': {
        key: 'dcat:accessURL',
        label: 'Access URL',
        type: 'uri',
        required: true,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'mandatory',
        icon: 'lucide:link',
        format: 'url',
        description: 'The URL that gives access to this distribution',
        placeholder: 'https://example.com/data, file://path/to/file, or s3://bucket/path',
    },
    'dcat:downloadURL': {
        key: 'dcat:downloadURL',
        label: 'Download URL',
        type: 'uri',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'optional',
        icon: 'lucide:download',
        format: 'url',
        description: 'Direct download link for this distribution',
        placeholder: 'https://example.com/data.csv',
    },
    'dcterms:title': {
        key: 'dcterms:title',
        label: 'Distribution Title',
        type: 'string',
        xsdType: 'xsd:string',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'optional',
        placeholder: 'e.g., CSV Export, DICOM Archive',
    },
    'dcterms:description': {
        key: 'dcterms:description',
        label: 'Description',
        type: 'string',
        xsdType: 'xsd:string',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'optional',
        placeholder: 'Describe this distribution',
    },
    'dcat:mediaType': {
        key: 'dcat:mediaType',
        label: 'Media Type',
        type: 'string',
        xsdType: 'xsd:string',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'recommended',
        vocabulary: 'fileType',
        placeholder: 'e.g., text/csv, application/json',
        description: 'IANA media type of the distribution',
    },
    'dcat:format': {
        key: 'dcat:format',
        label: 'Format',
        type: 'string',
        xsdType: 'xsd:string',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'recommended',
        placeholder: 'e.g., CSV, JSON, DICOM, NIfTI',
    },
    'dcat:byteSize': {
        key: 'dcat:byteSize',
        label: 'File Size (bytes)',
        type: 'number',
        xsdType: 'xsd:nonNegativeInteger',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'optional',
        placeholder: '0',
    },
    'dcterms:license': {
        key: 'dcterms:license',
        label: 'Licence',
        type: 'string',
        xsdType: 'xsd:string',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'recommended',
        description: 'The licence for this specific distribution',
        placeholder: 'e.g., CC-BY-4.0, EUPL-1.2',
    },
    'dcatap:availability': {
        key: 'dcatap:availability',
        label: 'Availability',
        type: 'array',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'recommended',
        description: 'Planned availability of this distribution',
        children: {
            '@id': {
                key: '@id',
                label: 'Availability',
                type: 'uri',
                required: true,
                readonly: false,
                repeatable: false,
                vocabulary: 'availability',
                placeholder: 'http://data.europa.eu/r5r/AVAILABLE',
            },
            '@type': {
                key: '@type',
                label: 'Type',
                type: 'string',
                required: false,
                readonly: true,
                repeatable: false,
                hidden: true,
                defaultValue: 'skos:Concept',
            },
            'skos:prefLabel': {
                key: 'skos:prefLabel',
                label: 'Label',
                type: 'language-string',
                required: false,
                readonly: false,
                repeatable: false,
            },
        },
    },
    'dcterms:issued': {
        key: 'dcterms:issued',
        label: 'Release Date',
        type: 'date',
        xsdType: 'xsd:dateTime',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'optional',
    },
    'dcterms:modified': {
        key: 'dcterms:modified',
        label: 'Last Updated',
        type: 'date',
        xsdType: 'xsd:dateTime',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'optional',
    },
    'spdx:checksum': {
        key: 'spdx:checksum',
        label: 'Checksum',
        type: 'object',
        required: false,
        readonly: false,
        repeatable: false,
        dcatApCompliance: 'optional',
        description: 'Checksum to verify file integrity',
        children: {
            '@id': {
                key: '@id',
                label: 'Checksum ID',
                type: 'uri',
                required: false,
                readonly: false,
                repeatable: false,
                hidden: true,
            },
            '@type': {
                key: '@type',
                label: 'Type',
                type: 'string',
                required: false,
                readonly: true,
                repeatable: false,
                hidden: true,
                defaultValue: 'spdx:Checksum',
            },
            'spdx:algorithm': {
                key: 'spdx:algorithm',
                label: 'Hash Algorithm',
                type: 'uri',
                required: false,
                readonly: false,
                repeatable: false,
                vocabulary: 'algorithm',
                description: 'The algorithm used (e.g., SHA-256)',
                placeholder: 'http://spdx.org/rdf/terms#SHA256',
            },
            'spdx:checksumValue': {
                key: 'spdx:checksumValue',
                label: 'Checksum Value',
                type: 'string',
                xsdType: 'xsd:hexBinary',
                format: 'hex',
                required: false,
                readonly: false,
                repeatable: false,
                placeholder: 'Hexadecimal checksum value',
            },
        },
    },
    'dcat:accessService': {
        key: 'dcat:accessService',
        label: 'Access Service',
        type: 'array',
        required: false,
        readonly: false,
        repeatable: true,
        dcatApCompliance: 'optional',
        description: 'A data service that gives access to this distribution',
        children: {
            '@id': {
                key: '@id',
                label: 'Service URI',
                type: 'uri',
                required: true,
                readonly: false,
                repeatable: false,
                hidden: true,
            },
            '@type': {
                key: '@type',
                label: 'Type',
                type: 'string',
                required: false,
                readonly: true,
                repeatable: false,
                hidden: true,
                defaultValue: 'dcat:DataService',
            },
            'dcterms:title': {
                key: 'dcterms:title',
                label: 'Service Title',
                type: 'language-string',
                required: false,
                readonly: false,
                repeatable: false,
                placeholder: 'e.g., SPARQL Endpoint',
            },
            'dcat:endpointURL': {
                key: 'dcat:endpointURL',
                label: 'Endpoint URL',
                type: 'uri',
                required: false,
                readonly: false,
                repeatable: false,
                format: 'url',
                placeholder: 'https://example.com/sparql',
                description: 'URL of the service endpoint',
            },
            'dcat:endpointDescription': {
                key: 'dcat:endpointDescription',
                label: 'Endpoint Description',
                type: 'uri',
                required: false,
                readonly: false,
                repeatable: false,
                format: 'url',
                description: 'URI describing the endpoint (e.g., OpenAPI spec)',
            },
        },
    },
};
