/**
 * Composable for generating unique IDs for JSON-LD entities
 */
export function useIdGenerator() {
    /**
     * Generate a unique Dataset ID
     * Format: urn:uuid:dataset-{timestamp}-{random}
     */
    const generateDatasetId = (): string => {
        const timestamp = Date.now();
        const random = Math.random().toString(36).substring(2, 9);
        return `urn:uuid:dataset-${timestamp}-${random}`;
    };

    /**
     * Generate a Distribution ID based on parent Dataset ID
     * Format: {datasetId}/distribution/{index}
     */
    const generateDistributionId = (datasetId: string, index: number): string => {
        // Remove urn:uuid: prefix if present for cleaner URLs
        const cleanId = datasetId.replace('urn:uuid:', '');
        return `urn:uuid:${cleanId}/distribution/${index}`;
    };

    /**
     * Generate a generic entity ID
     * Format: urn:uuid:{type}-{timestamp}-{random}
     */
    const generateEntityId = (type: string): string => {
        const timestamp = Date.now();
        const random = Math.random().toString(36).substring(2, 9);
        return `urn:uuid:${type}-${timestamp}-${random}`;
    };

    /**
     * Check if an ID looks auto-generated
     */
    const isAutoGeneratedId = (id: string): boolean => {
        return id.startsWith('urn:uuid:') && /-([\d]+)-([a-z0-9]+)/.test(id);
    };

    return {
        generateDatasetId,
        generateDistributionId,
        generateEntityId,
        isAutoGeneratedId,
    };
}
