name: Build and push docker image

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'releases/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: hiro-microdatacenters-bv/nextgen-fe

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make versions
        run: |
          cd "${{ github.workspace }}"
          chmod +x ./tools/version.sh
          ./tools/version.sh "${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}"
          echo "VERSION_APP=$(cat "./VERSION_APP")" >> $GITHUB_ENV
          echo "DOCKER_IMAGES=$(cat "./DOCKER_IMAGES")" >> $GITHUB_ENV
          echo "DOCKER_TAGS=$(cat "./VERSION_DOCKER")" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: ${{ env.DOCKER_TAGS }}

      - name: Push docker image with version
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGES }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
          build-args: |
            NUXT_PUBLIC_APP_VERSION: ${{ env.VERSION_APP }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create a github release
        run: gh release create "${{ env.VERSION_APP }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ github.token }}
          target_dir: "./helm-charts/"
